/* This is a React component for a chatbot interface. It manages user input, sends messages to a backend API, 
and displays the conversation. The component includes loading state management to prevent multiple submissions and 
provides feedback to the user during message processing. 

!!!NOTE: The setIsLoading state was generated by AI and used as an idea for loading state management.!!!
*/
"use client";
import React from 'react'
import {useState } from "react";
interface Message {
  role: string;
  content: string;
}
const Chatbot = () => {
    const [messages, setMessages] = useState<Message[]>([]);
    const [input, setInput] = useState("");
    const [isLoading, setIsLoading] = useState(false);
    
    const submitChat = async (e: React.FormEvent) => {
        e.preventDefault();

        //avoid sending empty messages
        if (!input.trim() || isLoading) return;
        
        // Set loading state to true
        setIsLoading(true);
    
        // Create a new message object
        const newMessage = {
        role: "user",
        content: input,
        };
    
        //add user message to chat
        setMessages((prev) => [...prev, newMessage]);
    
        // send message to backend
        const response = await fetch('/api/chatbot', {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({ 
          query: input, 
          conversation_history: messages
        }),
        });
    
        if (response.ok) {
        const data = await response.json();
        const aiMessage = {
            role: "assistant",
            content: data.reply,
        };
        //add assistant message to chat
        setMessages((prev) => [...prev, aiMessage]);
        } 
        else {
        const systemMessage = {
            role: "system",
            content: 'Sorry, could not fetch chat response. Please try again later.',
        };
        
        //add system message to chat
        setMessages((prev) => [...prev, systemMessage]);
        }
    
        // Clear input field and reset loading state
        setInput("");
        setIsLoading(false);
    };
  return (
    <>
    <div className="mt-16 border-2 border-secondary rounded bg-gray-50 w-full flex flex-col h-[500px]">
          <div className="flex-grow p-4 overflow-y-auto">
            {messages.length === 0 ? (
              <h4 className="text-black text-center mt-20 select-none">
                Hello! Send a message to start a conversation.
              </h4>
            ) : (
              messages.map((msg, index) => (
                <div 
                  key={index} 
                  className={`mb-10 p-3 rounded-lg max-w-[60%] break-words whitespace-normal 
                  ${
                    msg.role === "user" 
                      ? "bg-primary text-white ml-auto" 
                      : msg.role === "assistant"
                      ? "bg-gray-200 text-gray-800 mr-auto"
                      : "bg-amber-100 text-amber-800 mx-auto text-center"
                  }`}
                >
                  {msg.content}
                </div>
              ))
            )}
          </div>
          <form onSubmit={submitChat} className="p-4 border-t border-gray-200">
            <div className="relative w-full">
              <input
                type="text"
                value={input}
                maxLength={500}
                onChange={(e) => setInput(e.target.value)}
                disabled={isLoading}
                placeholder={"Type your message..."}
                className={`w-full font-family-[Rubik] py-2 pl-4 pr-32 border border-gray-300 rounded-full text-left \
                focus:outline-none focus:ring-2 focus:ring-primary ${isLoading ? 'bg-gray-100 cursor-not-allowed' : ''}`}
              />
              <div className="absolute flex space-x-0.5 right-1 top-1/2 transform -translate-y-1/2">
                <button
                  disabled={isLoading}
                  className={`flex-shrink-0 px-4 py-1.5 border-primary-200 bg-primary text-white rounded-l-full transition-all 
                  ${!isLoading ? 'hover:bg-secondary hover:scale-105 cursor-pointer' :'opacity-60 cursor-not-allowed'}`}
                >
                  @
                </button>
                <button
                  type="submit"
                  disabled={isLoading}
                  className={`flex-shrink-0 px-4 py-1.5 border-primary-200 bg-primary text-white rounded-r-full transition-all 
                  ${!isLoading ? 'hover:bg-secondary hover:scale-105 cursor-pointer' : 'opacity-60 cursor-not-allowed'}`}
                >
                  {isLoading ? '...' : 'Send'}
                </button>
              </div>
            </div>
          </form>
        </div>
    </>
  )
}

export default Chatbot